name: untitled
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  url_launcher: ^6.0.20
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter_icons:
  android: true
  image_path: "assets/Android/photo5873080513143617727.jpg"

flutter:

  uses-material-design: true
fonts:
  - family: Eczar
    fonts:
      - asset: assets/fonts/Eczar-SemiBold.ttf
        weight: 400
  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather-Regular.ttf
        weight: 400
